<?php

namespace yozh\crud\controllers;

use yozh\crud\interfaces\ActiveRecordInterface;
use yozh\crud\interfaces\CrudInterface;
use yozh\crud\traits\CRUDTrait;
use yozh\crud\models\BaseModel;
use yozh\crud\AssetBundle;

use yozh\base\controllers\DefaultController as Controller;

abstract class DefaultController extends Controller implements CrudInterface
{
	use CRUDTrait {
		actionIndex as protected traitActionIndex;
	}
	
	/**
	 * @return BaseModel::class
	 */
	abstract public static function defaultModelClass();
	
	public function actionIndex()
	{
		return $this->traitActionIndex();
	}
	
	public function beforeAction( $action
	)
	{
		AssetBundle::register( $this->view );
		
		return parent::beforeAction( $action );
	}
	
	protected function _findModel( $condition, $modelClass = null, $one = true )
	{
		$modelClass = static::defaultModelClass();
		
		return parent::_findModel( $condition, $modelClass, $one ); // TODO: Change the autogenerated stub
	}
	
}
