<?php

namespace yozh\crud;

use Yii;

class AssetBundle extends \yii\web\AssetBundle
{

    public $sourcePath = __DIR__ .'/../assets/';
	
	public $css = [
		'css/yozh-crud.css',
		//['css/yozh-settings.print.css', 'media' => 'print'],
	];
	
	public $js = [
		'js/yozh-crud.js',
	];
	
	public $depends = [
		\yozh\form\AssetBundle::class,
	];
	
	public $publishOptions = [
		'forceCopy'       => true,
	];
	
	public function registerAssetFiles( $view )
	{
		$filename = str_replace( '/', '-', Yii::$app->controller->route );
		
		if( is_file( "{$this->sourcePath}/js/$filename.js" ) ){
			$this->js[] = "js/$filename.js";
		}
		
		if( is_file( "{$this->sourcePath}/css/$filename.css" ) ){
			$this->css[] = "css/$filename.css";
		}
		
		parent::registerAssetFiles( $view ); // TODO: Change the autogenerated stub
	}
	
}