<?php
/**
 * Created by PhpStorm.
 * User: bw_dev
 * Date: 22.11.2018
 * Time: 15:09
 */

namespace yozh\crud\widgets;

use yii\base\Model;
use yii\helpers\Html;
use yii\helpers\Url;
use yozh\form\ActiveField;
use yozh\base\components\helpers\ArrayHelper;

class ActiveForm extends \yozh\form\ActiveForm
{
	public function fields( Model $Model, $attributes = null, $params = [] )
	{
		static::$defaultFieldParams['nestedAttributes'] = [];
		static::$defaultFieldParams['print']            = false;
		
		/**
		 * @var Array|Closure $fields
		 */
		extract( ArrayHelper::setDefaults( $params, static::$defaultFieldParams, ArrayHelper::DEFAULTS_MODE_FILTER ) );
		
		if( $fields instanceof \Closure ) {
			
			$fields = $fields( $this, $Model, $attributes, $params );
			
		}
		
		$params['fields'] = &$fields;
		
		// convert $nestedAttributes to hidden if set
		if( $nestedAttributes ?? false ) {
			
			//$_except = array_unique( array_merge( array_keys( $nestedAttributes ), $Model->primaryKey() ) );
			
			foreach( ( $nestedAttributes ?? [] ) as $_name => $_value ) {
				if( in_array( $_name, $Model->attributes() ) ) {
					$fields[ $_name ] = $this->field( $Model, $_name, [ 'template' => '{input}', 'options' => [ 'tag' => null ] ] )->hiddenInput();
				}
			}
		}
		
		$fields = array_merge( parent::fields( $Model
			, $Model instanceof \yozh\form\interfaces\AttributeActionListInterface
				? $Model->attributesEditList()
				: $Model->attributes()
			, $params
		), $fields );
		
		return $fields; // TODO: Change the autogenerated stub
	}
	
	
}